name: Build caramelChat

on:
  push:
    branches: [ dev/1.20.1 ]
  pull_request:
    branches: [ dev/1.20.1 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: caramelChat-artifacts
          path: |
            fabric/build/libs/**.jar
            forge/build/libs/**.jar
  release:
    needs: build
    runs-on: ubuntu-slim
    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: caramelChat-artifacts
          path: artifacts
      - uses: actions/attest@v4
        id: attest
        with:
          subject-path: artifacts/**
      - name: Make release
        run: |
          gh release create \
            nightly.1.20.1.run.${{ github.run_id }} \
            $(find ./artifacts -type f -name '*.jar') \
            -p --notes "https://github.com/${{ github.repository }}/runs/${{ github.run_id }} (:octocat: Attestation: ${{ steps.attest.outputs.attestation-url }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}